name: Run arxiv_saver_to_db.py and commit changes

on:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install sqlite3
          pip install feedparser
          pip install requests
      - name: Run arxiv_saver_to_db.py
        run: python3 arxiv_saver_to_db.py
      - name: Commit changes
        run: |
          git config --global user.name "Giseop Kim"
          git config --global user.email "gisbi.kim@gmail.com"
          git add arxiv_papers.db
          git commit -m "Auto-commit changes to arxiv_papers.db"
          git push