name: Run arxiv_saver_to_db.py and commit changes

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install feedparser
          pip install requests
          
      - name: Run arxiv_saver_to_db.py
        run: python3 arxiv_saver_to_db.py

      - name: Push the updated db
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "Auto-commit changes to arxiv_papers.db"
          files: arxiv_papers.db
          rebase: 'true'
          name: ${{ env.MY_USER_NAME }}
          email: ${{ env.MY_USER_EMAIL }}
